{
    'name': 'Tug: Manufacturing Order: Mods, Reports',
    'version': '19.0.2.11',
    'category': 'Manufacturing',
    'summary': 'Custom Manufacturing Order Reports & Email Wizard',
    'depends': ['mrp', 'mail', 'stock'],
    'data': [
        'security/ir.model.access.csv',
        'reports/report_action.xml',
        'data/mail_template_data.xml',
        'data/printnode_setup_action.xml',
        'wizard/mrp_report_wizard_view.xml',
        'views/mrp_view.xml',
        'views/stock_picking_view.xml',
        'reports/report_internal_template.xml',
        'reports/report_external_template.xml',
        'reports/report_package_zpl_template.xml',
    ],
    'installable': True,
    'application': False,
}