{
    'name': 'Tug: Manufacturing Order: Mods, Reports',
    'version': '3.4',
    'category': 'Manufacturing',
    'summary': 'Custom Manufacturing Order Reports & Email Wizard (Odoo 19 Ready)',
    'depends': ['mrp', 'mail', 'stock'],
    'data': [
        'security/ir.model.access.csv',
        'reports/paperformat.xml',
        'reports/report_action.xml',
        'data/mail_template_data.xml',
        'data/printnode_setup_action.xml',
        'wizard/mrp_report_wizard_view.xml',
        'views/mrp_view.xml',
        'views/stock_picking_view.xml',
        'reports/report_internal_template.xml',
        'reports/report_external_template.xml',
        'reports/report_package_zpl_template.xml',
        'reports/report_package_sscc_zpl.xml',
        'reports/report_pallet_label.xml',
        'reports/report_qfm_067.xml',
        'reports/report_qfm_084.xml',
        'reports/report_qfm_091.xml',
        'reports/report_qfm_092.xml',
    ],
    'installable': True,
    'application': False,
}
